// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhseujqwwykayedrbwds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoc2V1anF3d3lrYXllZHJid2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMDQwMDAsImV4cCI6MjA1NTU4MDAwMH0.4QGJxahEi20NrgFvE1jddK1Azp-SlKKvQ9AIcTXChds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);